Refined Maroon Tarantula

medium

# DoS in `quoteOptoin , liquidate , transferMarginToFund,Order execution` when calls to Pyth Oracle fails

## Summary
Perpetual's core functions  `quoteOptoin , liquidate , transferMarginToFund,Order execution`
depends on the fetched price of the asset from Pyth network. 
However, If the Pyth Network is down , the call to Pyth Oracle will fail . Hence reverting the whole transaction involving the fetching of price.

Thus functions like `quoteOptoin , liquidate , transferMarginToFund,Order execution` will face Denial of service because of getPrice Reverting.

## Vulnerability Detail
The getPrice function gets the price from Pyth network which is a source of reliable data feeds.

```solidity

function getPrice(bytes32 priceFeedId) public view returns (uint256, uint256) {
        // We don't use pyth.getPrice(), so we can control when to revert with _maxPriceAge,
        // reverted with StalePrice if price.publishTime exceeds _maxPriceAge
        try _pyth.getPriceNoOlderThan(priceFeedId, _maxPriceAge) returns (PythStructs.Price memory price) {
            // Assumes base price is against quote
            return (_convertToUint256(price), price.publishTime);
        } catch (bytes memory reason) {
            revert LibError.OracleDataRequired(priceFeedId, reason);
        }
    }

    

    
```
This function handles things elegantly however , current implementation does not have a good way to handle with price fetch failures. Due to which the catch block will always revert the whole transaction and hence the entire call chain that has called getPrice 
at the first place.

According to [Pythnet - How to use Price Feeds ](https://docs.pyth.network/price-feeds/pythnet-price-feeds/best-practices#price-availability):

```markdown
Sometimes, Pyth will not be able to provide a current price for a product. 
This situation can happen for various reasons. 

For example, US equity markets only trade during certain hours, and outside those hours,
 it's not clear what an equity's price is. Alternatively, a network outage (at the internet level, blockchain level, 
or at multiple data providers) may prevent the protocol from producing new price updates.
(Such outages are unlikely, but integrators should still be prepared for the possibility.) 

In such cases, Pyth may return a stale price for the product.

Integrators should be careful to avoid accidentally using a stale price
```
Pyth network acknowledges that network can face scenarios when price feeds can be non-functional at sometimes.

The Protocol team was aware of it . That's why they have added the try catch block to handle revert case of price fetch.

However , instead of elgantly handling this with some fallback oracle , the protocol just reverts. Which is somehow similar to not even having the try catch block.

Pyth Network intends developers to add getPrice in try catch block so that in catch block , they can have some fallback mechanism 
for example fetching price from chainlink or uniswap v3 ( if available ).


## Impact
- During the outage events , the protocol users will face Denial of service because all of the core functionalities will be reverting or i would say non-functional

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/oracle/pythOracleAdapter/PythOracleAdapter.sol#L80-L89
## Tool used

Manual Review

## Recommendation
Add a fallack price fetch mechanism like chainlink or uniswap v3.